# the site's base url
baseURL = 'https://newburghcreatescommunity.com'

# the site's language code
languageCode = 'en-us'

# the site's title
title = 'newburgh creates community'

# custom parameters
[params] 

# the site's main description
    description = 'a place for people in the newburgh creates community - resources, projects, & information'

# menu items
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 80

  [[menu.main]]
    identifier = "first teams"
    name = "first teams"
    url = "/first-teams"
    weight = 30

  [[menu.main]]
    identifier = "buildlab"
    name = "buildlab"
    url = "/buildlab"
    weight = 35

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = 50

# allow markup to include html elements
[markup.goldmark.renderer]
  unsafe = true

[security]
  allowContent = ['.*']
