# the site's base url
baseURL = 'www.newburghcreatescommunity.com'

# the site's language code
languageCode = 'en-us'

# the site's title
title = 'newburgh creates community'

# custom parameters
[params] 

# the site's main description
    description = 'a place for people in the newburgh creates community - resources, projects, & information'

# menu items
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 20

  [[menu.main]]
    identifier = "first teams"
    name = "first teams"
    url = "/first-teams"
    weight = 30

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = 50

# allow markup to include html elements
[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = 0
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = 0
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = 0
